artifact_uri: file:///home/alex/Desktop/tfm_code/mlruns_cluster/765808768288744310/543c8d5b93bd42e1bcdcd15bf3877f69/artifacts
end_time: null
entry_point_name: ''
experiment_id: '765808768288744310'
lifecycle_stage: active
run_id: 543c8d5b93bd42e1bcdcd15bf3877f69
run_name: apr25_multiseed_k5_rfmatched
source_name: ''
source_type: 4
source_version: ''
start_time: 1777129970836
status: 1
tags: []
user_id: ac5725
