artifact_uri: file:///home/alex/Desktop/tfm_code/mlruns_cluster/765808768288744310/8cfa0d88d55b4e078e55fadada2d9ed6/artifacts
end_time: 1777437253794
entry_point_name: ''
experiment_id: '765808768288744310'
lifecycle_stage: active
run_id: 8cfa0d88d55b4e078e55fadada2d9ed6
run_name: fold_06_val_S10
source_name: ''
source_type: 4
source_version: ''
start_time: 1777437101629
status: 3
tags: []
user_id: ac5725
