artifact_uri: file:///home/alex/Desktop/tfm_code/mlruns_cluster/765808768288744310/a4f7bfcebebc4c1996d69c130ddbb337/artifacts
end_time: 1777383984626
entry_point_name: ''
experiment_id: '765808768288744310'
lifecycle_stage: active
run_id: a4f7bfcebebc4c1996d69c130ddbb337
run_name: fold_03_val_S05
source_name: ''
source_type: 4
source_version: ''
start_time: 1777383910415
status: 3
tags: []
user_id: ac5725
