artifact_uri: file:///home/alex/Desktop/tfm_code/mlruns_cluster/765808768288744310/43ef0dbdf8d14db2bd7a3c84ac167cfb/artifacts
end_time: 1777408841777
entry_point_name: ''
experiment_id: '765808768288744310'
lifecycle_stage: active
run_id: 43ef0dbdf8d14db2bd7a3c84ac167cfb
run_name: fold_06_val_S10
source_name: ''
source_type: 4
source_version: ''
start_time: 1777408156184
status: 3
tags: []
user_id: ac5725
