artifact_uri: file:///home/alex/Desktop/tfm_code/mlruns_cluster/765808768288744310/ef987efc178f413cb2adb2f43792fe83/artifacts
end_time: 1777430613336
entry_point_name: ''
experiment_id: '765808768288744310'
lifecycle_stage: active
run_id: ef987efc178f413cb2adb2f43792fe83
run_name: apr28_multiseed_k4_default_singlephase
source_name: ''
source_type: 4
source_version: ''
start_time: 1777420054560
status: 3
tags: []
user_id: ac5725
