artifact_uri: file:///home/alex/Desktop/tfm_code/mlruns_cluster/765808768288744310/7ee5cf0feebc4c10adb26ce1d7db4124/artifacts
end_time: 1777205014660
entry_point_name: ''
experiment_id: '765808768288744310'
lifecycle_stage: active
run_id: 7ee5cf0feebc4c10adb26ce1d7db4124
run_name: fold_05_val_S07
source_name: ''
source_type: 4
source_version: ''
start_time: 1777204940377
status: 3
tags: []
user_id: ac5725
