artifact_uri: file:///home/alex/Desktop/tfm_code/mlruns_cluster/765808768288744310/f9a8c7f1ff8a4ef6ab985d5c0ba0c65a/artifacts
end_time: 1777372121283
entry_point_name: ''
experiment_id: '765808768288744310'
lifecycle_stage: active
run_id: f9a8c7f1ff8a4ef6ab985d5c0ba0c65a
run_name: fold_08_val_S13
source_name: ''
source_type: 4
source_version: ''
start_time: 1777371948513
status: 3
tags: []
user_id: ac5725
