artifact_uri: file:///home/alex/Desktop/tfm_code/mlruns_cluster/765808768288744310/eed1664efb37446abacc99aba11dc76b/artifacts
end_time: 1777299613729
entry_point_name: ''
experiment_id: '765808768288744310'
lifecycle_stage: active
run_id: eed1664efb37446abacc99aba11dc76b
run_name: fold_04_val_S06
source_name: ''
source_type: 4
source_version: ''
start_time: 1777299560213
status: 3
tags: []
user_id: ac5725
