artifact_uri: file:///home/alex/Desktop/tfm_code/mlruns_cluster/765808768288744310/d911fda9c1354d0d8cd6adc99d5eaa0f/artifacts
end_time: 1777200476265
entry_point_name: ''
experiment_id: '765808768288744310'
lifecycle_stage: active
run_id: d911fda9c1354d0d8cd6adc99d5eaa0f
run_name: fold_07_val_S12
source_name: ''
source_type: 4
source_version: ''
start_time: 1777199889051
status: 3
tags: []
user_id: ac5725
