artifact_uri: file:///home/alex/Desktop/tfm_code/mlruns_cluster/765808768288744310/d0c431ff9f9f4d9bb2faae370e03ac7e/artifacts
end_time: 1777422656086
entry_point_name: ''
experiment_id: '765808768288744310'
lifecycle_stage: active
run_id: d0c431ff9f9f4d9bb2faae370e03ac7e
run_name: fold_04_val_S06
source_name: ''
source_type: 4
source_version: ''
start_time: 1777422064680
status: 3
tags: []
user_id: ac5725
