artifact_uri: file:///home/alex/Desktop/tfm_code/mlruns_cluster/765808768288744310/db25bc06adf147cfb0bceb9ab16a8807/artifacts
end_time: 1777205579429
entry_point_name: ''
experiment_id: '765808768288744310'
lifecycle_stage: active
run_id: db25bc06adf147cfb0bceb9ab16a8807
run_name: fold_01_val_S01
source_name: ''
source_type: 4
source_version: ''
start_time: 1777205487371
status: 3
tags: []
user_id: ac5725
