artifact_uri: file:///home/alex/Desktop/tfm_code/mlruns_cluster/765808768288744310/47aa88ebdeb340edbb28bbc4ba1e025b/artifacts
end_time: 1777300963619
entry_point_name: ''
experiment_id: '765808768288744310'
lifecycle_stage: active
run_id: 47aa88ebdeb340edbb28bbc4ba1e025b
run_name: fold_04_val_S06
source_name: ''
source_type: 4
source_version: ''
start_time: 1777300899885
status: 3
tags: []
user_id: ac5725
