artifact_uri: file:///home/alex/Desktop/tfm_code/mlruns_cluster/765808768288744310/a7fda56aa30f4cdf89aaa372e3e2b5b7/artifacts
end_time: 1777228002828
entry_point_name: ''
experiment_id: '765808768288744310'
lifecycle_stage: active
run_id: a7fda56aa30f4cdf89aaa372e3e2b5b7
run_name: fold_03_val_S05
source_name: ''
source_type: 4
source_version: ''
start_time: 1777227857885
status: 3
tags: []
user_id: ac5725
