artifact_uri: file:///home/alex/Desktop/tfm_code/mlruns_cluster/765808768288744310/e62bfa3a3e414f9b8bd4fe13cce5b9e5/artifacts
end_time: 1777304510241
entry_point_name: ''
experiment_id: '765808768288744310'
lifecycle_stage: active
run_id: e62bfa3a3e414f9b8bd4fe13cce5b9e5
run_name: fold_04_val_S06
source_name: ''
source_type: 4
source_version: ''
start_time: 1777304449292
status: 3
tags: []
user_id: ac5725
