artifact_uri: file:///home/alex/Desktop/tfm_code/mlruns_cluster/765808768288744310/de888357bc9d48b29840b9fb20d5baab/artifacts
end_time: null
entry_point_name: ''
experiment_id: '765808768288744310'
lifecycle_stage: active
run_id: de888357bc9d48b29840b9fb20d5baab
run_name: fold_02_val_S02
source_name: ''
source_type: 4
source_version: ''
start_time: 1777199219335
status: 1
tags: []
user_id: ac5725
