artifact_uri: file:///home/alex/Desktop/tfm_code/mlruns_cluster/765808768288744310/87aa18afc1d14993b7f6623f4874f36b/artifacts
end_time: null
entry_point_name: ''
experiment_id: '765808768288744310'
lifecycle_stage: active
run_id: 87aa18afc1d14993b7f6623f4874f36b
run_name: apr26_multiseed_k1_narrow
source_name: ''
source_type: 4
source_version: ''
start_time: 1777198691753
status: 1
tags: []
user_id: ac5725
