artifact_uri: file:///home/alex/Desktop/tfm_code/mlruns_cluster/765808768288744310/a0dd1cf23ef343ccb3e2ca0de1ec27a4/artifacts
end_time: 1777174911725
entry_point_name: ''
experiment_id: '765808768288744310'
lifecycle_stage: active
run_id: a0dd1cf23ef343ccb3e2ca0de1ec27a4
run_name: fold_04_val_S06
source_name: ''
source_type: 4
source_version: ''
start_time: 1777174849814
status: 3
tags: []
user_id: ac5725
