artifact_uri: file:///home/alex/Desktop/tfm_code/mlruns_cluster/765808768288744310/1cd4c68ffea94f158f7c3bff9cb0b0c0/artifacts
end_time: 1777378965200
entry_point_name: ''
experiment_id: '765808768288744310'
lifecycle_stage: active
run_id: 1cd4c68ffea94f158f7c3bff9cb0b0c0
run_name: fold_08_val_S13
source_name: ''
source_type: 4
source_version: ''
start_time: 1777378708944
status: 3
tags: []
user_id: ac5725
